remote_theme: thelehhman/plainwhite-jekyll
title: but why ?
description: technical blog trying to understand a bit further

plainwhite:
  name: Nicolas Dragon
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: nDragon33
